### ISSUE TITLE
A black screen always on top

### ISSUE THREAD

**Issue by Henryxjh** [avitran0/deadlocked#2]
When I start the cheat, It open a black window on top and I can't see anything from game except esp.
![image](https://github.com/user-attachments/assets/e75b3642-8eae-4241-b8ab-71ea77df3a7f)
![image](https://github.com/user-attachments/assets/231d9eb7-29c5-4613-842d-e26e19c58cca)
This is my system information.
![image](https://github.com/user-attachments/assets/f1b9a055-a175-4f75-bf7d-fafd7c48208c)

**Comment by Henryxjh** [comment]
It log something like took 100ms in visual/aimbot loop

**Comment by avitran0** [comment]
can you try running it with wayland, mot x11? on x it also had some bugfy behavior for me, but that could just be my install

**Comment by Henryxjh** [comment]
I test it on wayland, and the windows looks like this
![image](https://github.com/user-attachments/assets/eec4807e-5e23-414d-9414-8b3161b8f165)
and also test build from source code with different sdl3 version, other version didn't open the transparent window

**Comment by avitran0** [comment]
i'm gonna add some logging later, that should hopefully try to narrow it down

**Comment by Henryxjh** [comment]
Is the lader you wrote can still use?

**Comment by avitran0** [comment]
yes, that should work just fine, but open an issue if it doesn't

**Comment by avitran0** [comment]
please try the latest release, i added some logging and debug drawing options.

**Comment by Henryxjh** [comment]
here's the log i get:
![image](https://github.com/user-attachments/assets/259a3582-898e-4f70-a308-ed4cc6a9c7a2)

**Comment by avitran0** [comment]
when turning on overlay debugging in visuals, do you see anything?

**Comment by Henryxjh** [comment]
Noting. Everything same as before

**Comment by avitran0** [comment]
add me on discord @ avitrano and i hope we can get this resolved
