### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ParanoIIa91** [avitran0/deadlocked#3]
How do you exactly start it. I typed sudo usermod -aG input USERNAME in terminal then restarted and when typed cargo run --release i get command unknown
![Screenshot_20241207_221423](https://github.com/user-attachments/assets/b9683a4a-e65e-4089-93ac-18f1242d6b18)
?

**Comment by avitran0** [comment]
either download a precompiled binary from the releases tab, or install rust from https://rustup.rs/

**Comment by ParanoIIa91** [comment]
i downloaded deadlock file from releases but how do i launch it?

**Comment by avitran0** [comment]
in the terminal, when you are in the same directory as the binary: `./deadlocked`

**Comment by ParanoIIa91** [comment]
So i have file downloaded then i open that file in terminal and run cargo run --release but it still says command unknown?

**Comment by avitran0** [comment]
look, i'm not your linux help forum. this isn't on topic, just learn how to run programs or install rust by yourself. i even gave you the damn link.

**Comment by ParanoIIa91** [comment]
![Uploading image.png…]()

**Comment by ParanoIIa91** [comment]
Ok, so i installed rust then typed sudo usermod -aG input USERNAME and then release command but still it doesnt want to work?

**Comment by ParanoIIa91** [comment]
![Uploading Screenshot_20241209_173910.png…]()

**Comment by avitran0** [comment]
1. did you replace USERNAME with your actual user name?
2. what exactly does not work?
3. i am not your fucking linux guide, stop posting in this god damn issue
4. google it for yourself how to add a user to a group, or how to run a rust application

**Comment by ParanoIIa91** [comment]
![Screenshot_20241209_173910](https://github.com/user-attachments/assets/f3c4ecd6-9c84-4019-ac37-2a908f9b8caf)
Yes, i replaced username with actual username

**Comment by avitran0** [comment]
you didn't cd to the repository.

**Comment by ParanoIIa91** [comment]
![Screenshot_20241210_181039](https://github.com/user-attachments/assets/ad8d94bf-ee71-4f32-a1db-c407e2b3cbcf)
Still same even if you open deadlocked file in terminal?
