### ISSUE TITLE
It doesnt work.

### ISSUE THREAD

**Issue by ParanoIIa91** [avitran0/deadlocked#5]
![image](https://github.com/user-attachments/assets/19d77510-363a-47bf-b5c9-731e74988901)
I finally managed to open it, but when in game nothing is working, looks as usual, same for my gf? The only thing works is recoil compensation and maybe aimbot but even with 360 is not constant.

**Comment by avitran0** [comment]
does anything show when you turn on debug overlay in the visuals section? do you run on x11 or wayland? one thing to try for the aimbot would be to set the hotkey to something different, start bullet to 0, and just press it to see whether it locks on to players without shooting

**Comment by avitran0** [comment]
i just tried it, and yea the aimbot does not seem to want to work. i'll get on that as soon as i can.

**Comment by avitran0** [comment]
the aimbot branch works fine, if you want to just use that for now.

**Comment by ParanoIIa91** [comment]
I tried x11 and wayland and yet aimbot/aim lock doesnt work with the latest version, i changed bindings, fov to 360 and the only thing that works is recoil compensation, also what about wallhack?

**Comment by avitran0** [comment]
what is your config? did you put start bullet to 0 and visibility check off? if start bullet is above 0, it only works after a certain amount of bullets have been fired. as for the wallhack, again, i'm working on this. i an writing a c++ version, where the visuals should work better, but i don't have that much time, so please don't press me on this. if you don't like it, get another cheat.

**Comment by ParanoIIa91** [comment]
I am not complaining just reporting. So i turned off visibility check and its working but when i turn off aim lock it still locks to other enemies.

**Comment by avitran0** [comment]
what exactly do you mean? it locks onto enemies without aimlock on? if so, what value do you have for smoothing?

**Comment by ParanoIIa91** [comment]
Yes, the problem is that sometimes it forces you to spray over enemies heads and there is nothing you can do about it, even when dragging recoil down it gets stucks above head, so even with aimbot/aim lock aim kicks in pretty often and smoothing is on 5 now.

**Comment by avitran0** [comment]
if you only want the recoil control, then you just activate rcs and disable aimbot, simple as that

**Comment by ParanoIIa91** [comment]
Thats the thing it works randomly even when its off, i literally start shooting trough walls and smokes when i dont want to.

**Comment by avitran0** [comment]
you mean it presses the trigger or what? or that it does not check for visibility? there is an option for that, and no it literally cannot press a button to start shooting.

**Comment by ParanoIIa91** [comment]
No thats not what i mean, i mean aim hack works even with everything disabled other then multibone and RCS.

**Comment by avitran0** [comment]
would be good to make a video, easier for understanding what exactly you mean

**Comment by avitran0** [comment]
alright, i rewrote the esp part in c++, would be nice if you told me whether that works now. the aimbot part will come later, when i have more time to do that. you gotta compile it yourself, but should work fine by just running the run script, as long as you have a c++ compiler and cmake installed.

**Comment by avitran0** [comment]
also, you gotta clone it with `git clone --recursive`, so that it gets all dependencies.

**Comment by ParanoIIa91** [comment]
Ok, so i just tried latest compailed version with WH only and no matter which settings, it doesnt work or do anything, i can try to make a video but in simple words auto aim/lock kicks in randomly when its off, for example when spraying trough smoke i can get random headshoots, same when someone is behind walls, so in the middle off the spray crosshair would follow him behind it.

**Comment by ParanoIIa91** [comment]
Ok so i tried both x11 and wayland with wh only hack and no luck, doesnt do anything in game and often instead of displaying app i just see black screen with 119 fps displayed on the top left.

**Comment by avitran0** [comment]
> Ok, so i just tried latest compailed version with WH only and no matter which settings, it doesnt work or do anything, i can try to make a video but in simple words auto aim/lock kicks in randomly when its off, for example when spraying trough smoke i can get random headshoots, same when someone is behind walls, so in the middle off the spray crosshair would follow him behind it.

it would be good to have a video, i kind of get your explanation, but not fully. it can be that it continues to track an enemy that runs behind a wall/smoke for a second, because it uses cs2's built-in radar visibility check, which updates very slowly.

**Comment by avitran0** [comment]
> Ok so i tried both x11 and wayland with wh only hack and no luck, doesnt do anything in game and often instead of displaying app i just see black screen with 119 fps displayed on the top left.

well, overlays in linux are kinda borked, and your compositor orobably does not support transparency properly. there just isn't much i can do tbh. do you use the native linux or the proton version of cs2?

**Comment by ParanoIIa91** [comment]
I will try to record it and i use native version.
